const localIsoDate = (date) => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const today = new Date();
const iso = (offset) => {
  const date = new Date(today);
  date.setDate(today.getDate() + offset);
  return localIsoDate(date);
};

export const sessionTypes = [
  "Mobilite",
  "Force",
  "Endurance de force",
  "Volume",
  "Simulation",
  "Technique",
  "Renforcement",
  "Souplesse",
  "Autre",
  "Qual",
];

export const demoCycles = [
  {
    id: "cycle-force",
    name: "Bloc Force Max",
    start_date: iso(-7),
    end_date: iso(14),
    objective: "Monter la tension doigts sans exploser la fatigue",
    main_theme: "Force doigts",
    color: "pink",
  },
  {
    id: "cycle-volume",
    name: "Volume Qualitatif",
    start_date: iso(15),
    end_date: iso(36),
    objective: "Accumuler des mouvements propres en intensite moderee",
    main_theme: "Capacite",
    color: "green",
  },
];

export const demoSessions = [
  {
    id: "s-1",
    cycle_id: "cycle-force",
    cycle_ids: ["cycle-force"],
    name: "Max hangs + blocs durs",
    date: iso(-2),
    time: "18:30",
    duration: 95,
    location: "Bruxelles",
    objective: "Tension doigts et recrutement nerveux",
    notes: "Garder deux essais propres par bloc.",
    type: "Force",
    rpe: 8,
    internal_load: 76,
    predicted_muscular_form: 7,
    predicted_finger_form: 8,
    predicted_neural_form: 7,
    predicted_general_form: 7,
    success_rate: 72,
    motivation: 8,
    one_arm_hang_feeling: 7,
    explosive_pull_feeling: 8,
  },
  {
    id: "s-2",
    cycle_id: "cycle-force",
    cycle_ids: ["cycle-force"],
    name: "Technique talons et gainage",
    date: iso(1),
    time: "12:15",
    duration: 70,
    location: "Charleroi",
    objective: "Qualite de placement, intensite basse",
    notes: "Aucun run a l'echec.",
    type: "Technique",
    rpe: 5,
    internal_load: 35,
    predicted_muscular_form: 8,
    predicted_finger_form: 7,
    predicted_neural_form: 8,
    predicted_general_form: 8,
    success_rate: 82,
    motivation: 7,
    one_arm_hang_feeling: 6,
    explosive_pull_feeling: 7,
  },
  {
    id: "s-3",
    cycle_id: "cycle-force",
    cycle_ids: ["cycle-force", "cycle-volume"],
    name: "Volume voies courtes",
    date: iso(4),
    time: "10:00",
    duration: 110,
    location: "Nivelles",
    objective: "Densite sans perte de precision",
    notes: "",
    type: "Volume",
    rpe: 7,
    internal_load: 72,
    predicted_muscular_form: 6,
    predicted_finger_form: 6,
    predicted_neural_form: 7,
    predicted_general_form: 6,
    success_rate: 68,
    motivation: 8,
    one_arm_hang_feeling: 6,
    explosive_pull_feeling: 6,
  },
];

export const demoTelemetry = [
  {
    id: "t-1",
    date: iso(-3),
    sleep_quality: 7,
    bedtime: "23:00",
    wake_time: "07:00",
    naps_count: 0,
    naps_total_duration: 0,
    work_stress: 5,
    work_volume: 6,
    personal_stress: 4,
    work_satisfaction: 7,
    motivation: 7,
    confidence: 7,
    mood: 7,
    meditation: true,
    hydration: 8,
    breakfast_quality: 7,
    lunch_quality: 8,
    dinner_quality: 7,
    morning_mobility: true,
    soreness_index: 4,
    screen_interactions: 6,
  },
  {
    id: "t-2",
    date: iso(-2),
    sleep_quality: 8,
    bedtime: "22:45",
    wake_time: "06:45",
    naps_count: 0,
    naps_total_duration: 0,
    work_stress: 4,
    work_volume: 5,
    personal_stress: 3,
    work_satisfaction: 8,
    motivation: 8,
    confidence: 8,
    mood: 8,
    meditation: true,
    hydration: 8,
    breakfast_quality: 8,
    lunch_quality: 8,
    dinner_quality: 8,
    morning_mobility: true,
    soreness_index: 3,
    screen_interactions: 5,
  },
  {
    id: "t-3",
    date: iso(1),
    sleep_quality: 6,
    bedtime: "23:30",
    wake_time: "07:15",
    naps_count: 1,
    naps_total_duration: 20,
    work_stress: 6,
    work_volume: 7,
    personal_stress: 4,
    work_satisfaction: 6,
    motivation: 7,
    confidence: 6,
    mood: 6,
    meditation: false,
    hydration: 7,
    breakfast_quality: 6,
    lunch_quality: 7,
    dinner_quality: 7,
    morning_mobility: true,
    soreness_index: 5,
    screen_interactions: 8,
  },
  {
    id: "t-4",
    date: iso(4),
    sleep_quality: 7,
    bedtime: "23:00",
    wake_time: "07:30",
    naps_count: 0,
    naps_total_duration: 0,
    work_stress: 5,
    work_volume: 5,
    personal_stress: 5,
    work_satisfaction: 7,
    motivation: 8,
    confidence: 7,
    mood: 7,
    meditation: true,
    hydration: 8,
    breakfast_quality: 7,
    lunch_quality: 7,
    dinner_quality: 8,
    morning_mobility: false,
    soreness_index: 4,
    screen_interactions: 6,
  },
];
